# Generated by Django 5.2.7 on 2025-11-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0003_remove_klient_stanowisko_agent_stanowisko_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ['nazwisko']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metraż w m²', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Opis nieruchomości'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, help_text='Miasto lub dzielnica', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena nieruchomości', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='typical_features',
            field=models.CharField(blank=True, help_text='Typowe cechy tego typu nieruchomości.', max_length=200),
        ),
    ]
