# Generated by Django 5.2.7 on 2025-11-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0004_alter_agent_options_alter_klient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='square_meters',
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, help_text='Miasto, dzielnica, Kraj', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena nieruchomości (EUR)', max_digits=12, null=True),
        ),
    ]
