# Generated by Django 5.2.7 on 2025-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0005_rename_area_property_square_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena nieruchomości (EUR) lub Miesięczny koszt wynajmu (EUR)', max_digits=12, null=True),
        ),
    ]
