# Generated by Django 5.2.7 on 2025-11-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0006_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='AC',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma klimatyzacja?'),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma balkon?'),
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma garaz lub prywatne miejsce parkingowe?'),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma ogród?'),
        ),
        migrations.AddField(
            model_name='property',
            name='jacuzzi',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma jacuzzi?'),
        ),
        migrations.AddField(
            model_name='property',
            name='lift',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma windę?'),
        ),
        migrations.AddField(
            model_name='property',
            name='needs_renovation',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość jest do remontu?'),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma basen?'),
        ),
        migrations.AddField(
            model_name='property',
            name='safety_system',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma alarm lub całodobową ochronę?'),
        ),
        migrations.AddField(
            model_name='property',
            name='sauna',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma saunę?'),
        ),
        migrations.AddField(
            model_name='property',
            name='terrace',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma taras?'),
        ),
    ]
