# Generated by Django 5.2.7 on 2026-01-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0010_remove_klient_wlasciciel_klient_agenci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='agenci',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='klient',
            name='opiekun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moi_klienci', to='portal_nieruchomosci.agent'),
        ),
        migrations.AddField(
            model_name='klient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='stanowisko',
            field=models.CharField(choices=[('A', 'Agent nieruchomości'), ('D', 'Doradca sprzedaży'), ('O', 'Osoba prywatna'), ('F', 'Firma')], default='A', max_length=1),
        ),
    ]
