# Generated by Django 5.2.7 on 2026-01-23 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0011_remove_klient_agenci_remove_property_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena nieruchomości (EUR) lub Miesięczny koszt wynajmu (EUR)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metraż w m²', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
