# Generated by Django 5.2.7 on 2026-01-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0012_klient_email_alter_property_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
