# Generated by Django 5.2.8 on 2026-01-29 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0014_alter_property_ac_alter_property_balcony_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='stanowisko',
        ),
        migrations.AlterField(
            model_name='property',
            name='AC',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma klimatyzacja?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma balkon?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma garaz lub prywatne miejsce parkingowe?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma ogród?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='jacuzzi',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma jacuzzi?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lift',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma windę?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='needs_renovation',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość jest do remontu?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pool',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma basen?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena nieruchomości (EUR) lub Miesięczny koszt wynajmu (EUR)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='safety_system',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma alarm lub całodobową ochronę?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sauna',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma saunę?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='terrace',
            field=models.BooleanField(default=True, help_text='Czy nieruchomość ma taras?'),
        ),
    ]
