# Generated by Django 5.2.8 on 2026-01-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0015_remove_agent_stanowisko_alter_property_ac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='AC',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma klimatyzacja?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma balkon?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma garaz lub prywatne miejsce parkingowe?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma ogród?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='jacuzzi',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma jacuzzi?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lift',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma windę?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='needs_renovation',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość jest do remontu?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pool',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma basen?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='safety_system',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma alarm lub całodobową ochronę?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sauna',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma saunę?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='terrace',
            field=models.BooleanField(default=False, help_text='Czy nieruchomość ma taras?'),
        ),
    ]
