# Generated by Django 5.2.8 on 2026-01-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0016_alter_property_ac_alter_property_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(help_text='Kod regionu lub kraju, np. PL, DE, CZ', max_length=3),
        ),
    ]
